version: "3.4"

services:
  agent:
    build:
      target: debug
    ports:
      - "80:8080"
      - "2345:2345"
    volumes:
      - .:/app

  server:
    build:
      target: debug
    ports:
      - "81:8080"
      - "2346:2345"
    volumes:
      - .:/app


