FROM golang:1.21.3 AS debug

WORKDIR /app

RUN CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

CMD ["sh", "-c", "air --build.cmd 'go build -o bin/agent cmd/agent/main.go' --build.bin './bin/agent'"]

FROM golang:1.21.3 AS build

WORKDIR /app

COPY . .

RUN go build -o bin/agent cmd/agent/main.go

FROM golang:1.21.3 AS production

WORKDIR /app

COPY --from=build /app/bin/agent ./main

CMD [ "./main" ]
