FROM golang:1.21.3 AS debug

WORKDIR /app

RUN CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

CMD ["sh", "-c", "air --build.cmd 'go build -o bin/agent cmd/agent/main.go' --build.bin './bin/agent -a=http://server:8080 -r=10 -p=2'"]

FROM golang:1.21.3 AS build

WORKDIR /app

COPY . .

RUN go build -o bin/agent cmd/agent/main.go

FROM golang:1.21.3 AS production

WORKDIR /app

COPY --from=build /app/bin/agent ./main

CMD [ "./main", "-a=http://server:8080", "-r=10", "-p=2" ]


FROM golang:1.21.5-alpine3.17 AS build-tests

WORKDIR /app

COPY . .

RUN go build -o bin/agent cmd/agent/main.go
RUN go build -o bin/server cmd/server/main.go

FROM --platform=linux/amd64 golang:1.21.3 AS tests

WORKDIR /app

COPY --from=build-tests /app/bin/agent ./agent
COPY --from=build-tests /app/bin/agent ./server

COPY /local-tests/metricstest /usr/local/bin/metricstest

RUN chmod +x /usr/local/bin/metricstest

CMD ["metricstest", "-test.v", "-test.run=^TestIteration4$", "-agent-binary-path=/app/agent", "-binary-path=/app/server", "-server-port=8080"]
