FROM golang:1.21.5-bookworm AS debug

WORKDIR /app

RUN CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

CMD ["sh", "-c", "air --build.cmd 'go build -o bin/server cmd/server/main.go' --build.bin './bin/server -a=:8080'"]

FROM golang:1.21.5-alpine3.17 AS build

WORKDIR /app

COPY . .

RUN go build -o bin/server cmd/server/main.go

FROM golang:1.21.5-alpine3.17 AS production

WORKDIR /app

COPY --from=build /app/bin/server ./main

CMD [ "./main"]